### ISSUE TITLE
Found a serious security problem.

### ISSUE THREAD

**Issue by 0b01010001** [ryanb/ruby-warrior#89]
I can define arbitrary methods on protected classes inside Ruby Warrior, sketchy code working just fine. Reluctant to post the details in public, because, you know. Who's maintaining the site?

**Comment by ckuhn203** [comment]
This is the repository for the code project. The website is unaffiliated. I couldn't find a contact for the people running the game, but it's hosted on bloc.io and you can contact them here. mailto:hello@bloc.io

**Comment by 0b01010001** [comment]
Thanks. Is the sketchy code bit for their site a common implementation from here or their own thing? Haven't had time to dig into the code here much.

**Comment by 0b01010001** [comment]
Nevermind, thanks for the address in any case. Sorry for bringing this up in the wrong place!
