### ISSUE TITLE
Login with facebook error.

### ISSUE THREAD

**Issue by EgorOvechkin** [ryanb/ruby-warrior#96]
When I complited 1st level i must login with facebook. And when I clicked on the button i got
 `Ruh Roh.
Looks like something broke.
We have been notified of the problem and are looking into it, sorry for the inconvenience.`
and 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)` 
in console

**Comment by bf4** [comment]
@EgorOvechkin This repo is just the command-line game.  The website based on it is made by someone else.

**Comment by EgorOvechkin** [comment]
@bf4 Oh, sory for my inattention. I'll try to use cli version. Thank you.
