### ISSUE TITLE
are there any ports of ruby-warrior?

### ISSUE THREAD

**Issue by yegeniy** [ryanb/ruby-warrior#97]
Python / Java / JavaScript / etc..

Is there any interest in this?

Anyone aware of similar apps? I've seen http://play.elevatorsaga.com/

Would curating a list like this in the Wiki be of interest to anyone?

**Comment by joehenriod** [comment]
There is Javascript port called Warrior JS.

https://github.com/olistic/warriorjs

**Comment by vayerx** [comment]
Python implementation of ruby-warrior: https://github.com/arbylee/python-warrior
